name: CI Workflow

# Triggers the workflow on push or pull request events
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    # The job will run on the latest version of Ubuntu
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up the appropriate environment (this example uses Node.js)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Install dependencies (modify this step according to your project)
      - name: Install dependencies
        run: npm install

      # Run the tests (modify this step according to your project's testing framework)
      - name: Run tests
        run: npm test

      # Build the project (this step can be omitted if your project doesn't have a build step)
      - name: Build project
        run: npm run build
